version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Image
          command: |
            set +o pipefail
            TAG="$(cat VERSION)"
            docker build --build-arg TENSORFLOW_NOTEBOOK_TAG=${TAG} -t floydev/jupyter-notebook:${TAG} .
            docker tag floydev/jupyter-notebook:${TAG} floydev/jupyter-notebook:latest
      - run:
          name: Push the Image
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            TAG="$(cat VERSION)"
            docker push floydev/jupyter-notebook:${TAG}
            docker push floydev/jupyter-notebook:latest
workflows:
  version: 2
  build_pipeline:
    jobs:
      - build:
          filters:
            branches:
              only: master
